function tests = test_logging_prune_audit
%TEST_LOGGING_PRUNE_AUDIT MATLAB-side schema harness for issue #4397.
%
% This file is intentionally lightweight: CI hosts without a runnable Simulink
% 3D fullbody model can still use the Python static tests for the JSON schema,
% while MATLAB hosts can adapt the helper below to a loaded fixture model.

    tests = functiontests(localfunctions);
end


function testAuditSchemaHasRequiredFields(testCase)
    audit = local_minimal_audit_fixture();
    required = [ ...
        "schema_version", ...
        "source_model", ...
        "target_model", ...
        "measured_counts", ...
        "heuristic_estimates", ...
        "disabled_block_paths", ...
        "disabled_outport_paths", ...
        "category_breakdown", ...
        "downstream_signal_requirements", ...
        "candidates"];
    for i = 1:numel(required)
        verifyTrue(testCase, isfield(audit, required(i)), required(i));
    end
    verifyFalse(testCase, audit.heuristic_estimates.is_measured);
    verifyTrue(testCase, audit.downstream_signal_requirements.preserved);
end


function testDryRunCandidatesDoNotMutate(testCase)
    audit = local_minimal_audit_fixture();
    verifyTrue(testCase, audit.dry_run);
    for i = 1:numel(audit.candidates)
        verifyFalse(testCase, audit.candidates(i).mutated);
    end
end


function audit = local_minimal_audit_fixture()
    count = struct("value", 12, "measured", true);
    audit = struct( ...
        "schema_version", "3d_fullbody_logging_prune_audit.v1", ...
        "dry_run", true, ...
        "source_model", struct("path", "source.slx", "exists", false, "timestamp", "", "sha256", ""), ...
        "target_model", struct("path", "target.slx", "exists", false, "timestamp", "", "sha256", ""), ...
        "measured_counts", struct( ...
            "before", struct("total_blocks", count, "nonvirtual_blocks", count, "logged_signal_count", count), ...
            "after", struct("total_blocks", count, "nonvirtual_blocks", count, "logged_signal_count", count)), ...
        "heuristic_estimates", struct("disabled_signal_count", 1, "estimated_nonvirtual_block_savings", 1, "is_measured", false), ...
        "disabled_block_paths", strings(0, 1), ...
        "disabled_outport_paths", "model/ClubLocalForce", ...
        "category_breakdown", struct("local_global_club_duplicates", 1), ...
        "downstream_signal_requirements", struct("preserved", true, "allowlist", "ClubGlobalForce"), ...
        "candidates", struct("category", "local_global_club_duplicates", "kind", "outport", "path", "model/ClubLocalForce", "property", "SrcPortHandle.DataLogging", "action", "set logging off", "mutated", false));
end
