"""Simulation Data Store for High-Frequency Golf Swing Data.

This module provides the core interfaces for storing, querying, and managing
high-frequency kinematic and kinetic data generated by the physical models
(e.g., Pinocchio/Drake) and motion capture systems. It acts as the backbone
for training Physics-Informed Neural Networks (PINNs).

Persistence is implemented with HDF5 (via ``h5py``) when a ``storage_path``
is provided.  If no path is given the store operates in pure in-memory mode
and ``flush_to_disk`` / ``load_from_disk`` are safe no-ops.

Example::

    >>> from src.shared.data_store.store import SimulationDataStore, SwingDataSequence
    >>> import numpy as np
    >>> store = SimulationDataStore()
    >>> seq = SwingDataSequence(
    ...     sequence_id="run-001",
    ...     timestamps=np.linspace(0, 1, 10),
    ...     joint_angles=np.zeros((10, 6)),
    ...     joint_velocities=np.zeros((10, 6)),
    ...     club_pose=np.zeros((10, 7)),
    ...     applied_torques=np.zeros((10, 6)),
    ... )
    >>> store.add_sequence(seq)
    >>> store.list_sequences()
    ['run-001']
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)

_HDF5_GROUP = "sequences"


@dataclass
class SwingDataSequence:
    """Represents a single time-series sequence of a golf swing.

    Attributes:
        sequence_id: Unique identifier for this sequence.
        timestamps: Shape ``(N,)`` — simulation time steps in seconds.
        joint_angles: Shape ``(N, num_joints)`` — joint angles in radians.
        joint_velocities: Shape ``(N, num_joints)`` — joint velocities in rad/s.
        club_pose: Shape ``(N, 7)`` — quaternion (4) + translation (3).
        applied_torques: Shape ``(N, num_joints)`` — torques in N·m.
        metadata: Arbitrary string key/value annotations.

    Contract:
        Post: all array shapes consistent with ``len(timestamps)``.
    """

    sequence_id: str
    timestamps: np.ndarray
    joint_angles: np.ndarray
    joint_velocities: np.ndarray
    club_pose: np.ndarray
    applied_torques: np.ndarray
    metadata: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate array dimensions after initialisation.

        Raises:
            ValueError: If any array's first dimension differs from
                ``len(timestamps)``.
        """
        n_steps = len(self.timestamps)
        checks: list[tuple[str, np.ndarray]] = [
            ("joint_angles", self.joint_angles),
            ("joint_velocities", self.joint_velocities),
            ("club_pose", self.club_pose),
            ("applied_torques", self.applied_torques),
        ]
        for name, arr in checks:
            if len(arr) != n_steps:
                raise ValueError(
                    f"Mismatched dimensions: timestamps has {n_steps} steps "
                    f"but {name} has {len(arr)} rows."
                )


class SimulationDataStore:
    """In-memory (or HDF5-backed) store for golf simulation sequences.

    When ``storage_path`` is ``None`` the store is purely in-memory.
    When a path is provided, ``flush_to_disk()`` serialises all sequences
    to an HDF5 file and ``load_from_disk()`` deserialises them back.

    Contract:
        Pre  (add_sequence):  sequence is not None and sequence_id is non-empty.
        Pre  (get_sequence):  sequence_id is a non-empty string.
        Post (flush_to_disk): if storage_path is set, file exists afterwards.
        Post (load_from_disk): sequences already present are preserved; disk
            sequences are merged in (disk wins on collision).
    """

    def __init__(self, storage_path: str | None = None) -> None:
        """Initialise the data store.

        Args:
            storage_path: Optional path to an HDF5 file.  The file is created
                on ``flush_to_disk()`` — it need not exist yet.
                If ``None``, operates in pure in-memory mode.
        """
        self._storage_path: Path | None = (
            Path(storage_path) if storage_path is not None else None
        )
        self._sequences: dict[str, SwingDataSequence] = {}
        logger.debug(
            "SimulationDataStore initialised (path=%s)",
            self._storage_path or "in-memory",
        )

    # ------------------------------------------------------------------
    # Public CRUD
    # ------------------------------------------------------------------

    def add_sequence(self, sequence: SwingDataSequence) -> None:
        """Add a new swing sequence to the store.

        Args:
            sequence: The sequence to store.

        Raises:
            TypeError:  If ``sequence`` is not a :class:`SwingDataSequence`.
            ValueError: If ``sequence.sequence_id`` is empty.
            KeyError:   If a sequence with the same ID already exists.
        """
        if sequence is None:
            raise TypeError("sequence must not be None")
        if not isinstance(sequence, SwingDataSequence):
            raise TypeError(
                f"sequence must be a SwingDataSequence, got {type(sequence).__name__}"
            )
        if not sequence.sequence_id:
            raise ValueError("sequence.sequence_id must be a non-empty string")
        if sequence.sequence_id in self._sequences:
            raise KeyError(
                f"Sequence '{sequence.sequence_id}' already exists. "
                "Use a different ID or remove it first."
            )
        self._sequences[sequence.sequence_id] = sequence
        logger.debug("Added sequence '%s'", sequence.sequence_id)

    def get_sequence(self, sequence_id: str) -> SwingDataSequence:
        """Retrieve a sequence by its ID.

        Args:
            sequence_id: ID of the sequence to retrieve.

        Returns:
            The requested :class:`SwingDataSequence`.

        Raises:
            ValueError: If ``sequence_id`` is empty.
            KeyError:   If no sequence with that ID exists.
        """
        if not sequence_id:
            raise ValueError("sequence_id must be a non-empty string")
        return self._sequences[sequence_id]

    def list_sequences(self) -> list[str]:
        """Return a sorted list of all sequence IDs.

        Returns:
            Sorted list of sequence identifier strings.
        """
        return sorted(self._sequences.keys())

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def flush_to_disk(self) -> None:
        """Serialise all in-memory sequences to the HDF5 ``storage_path``.

        If ``storage_path`` is ``None`` this method is a safe no-op.

        Raises:
            ImportError: If ``h5py`` is not installed (should not happen
                since it is listed as a project dependency).
            OSError:     If the file cannot be written.
        """
        if self._storage_path is None:
            logger.debug("flush_to_disk: no storage_path configured, skipping.")
            return

        import h5py  # local import — h5py is an optional-heavy dep

        self._storage_path.parent.mkdir(parents=True, exist_ok=True)

        with h5py.File(self._storage_path, "w") as hf:
            grp = hf.require_group(_HDF5_GROUP)
            for seq_id, seq in self._sequences.items():
                sg = grp.require_group(_hdf5_key(seq_id))
                sg.attrs["sequence_id"] = seq_id
                sg.create_dataset("timestamps", data=seq.timestamps)
                sg.create_dataset("joint_angles", data=seq.joint_angles)
                sg.create_dataset("joint_velocities", data=seq.joint_velocities)
                sg.create_dataset("club_pose", data=seq.club_pose)
                sg.create_dataset("applied_torques", data=seq.applied_torques)
                # Persist metadata as HDF5 attributes
                for k, v in seq.metadata.items():
                    sg.attrs[f"meta_{k}"] = v

        logger.info(
            "Flushed %d sequence(s) to %s",
            len(self._sequences),
            self._storage_path,
        )

    def load_from_disk(self) -> None:
        """Load sequences from the HDF5 ``storage_path`` into memory.

        Sequences already present in memory are preserved; on collision the
        on-disk version wins.

        If ``storage_path`` is ``None`` or the file does not exist this
        method is a safe no-op.

        Raises:
            ImportError: If ``h5py`` is not installed.
            OSError:     If the file cannot be read.
        """
        if self._storage_path is None:
            logger.debug("load_from_disk: no storage_path configured, skipping.")
            return
        if not self._storage_path.exists():
            logger.debug(
                "load_from_disk: file %s does not exist, skipping.",
                self._storage_path,
            )
            return

        import h5py  # local import

        with h5py.File(self._storage_path, "r") as hf:
            if _HDF5_GROUP not in hf:
                logger.warning(
                    "load_from_disk: group '%s' not found in %s",
                    _HDF5_GROUP,
                    self._storage_path,
                )
                return

            grp = hf[_HDF5_GROUP]
            for key in grp:
                sg = grp[key]
                seq_id: str = str(sg.attrs.get("sequence_id", key))
                meta: dict[str, str] = {
                    str(k)[5:]: str(v)
                    for k, v in sg.attrs.items()
                    if str(k).startswith("meta_")
                }
                seq = SwingDataSequence(
                    sequence_id=seq_id,
                    timestamps=np.array(sg["timestamps"]),
                    joint_angles=np.array(sg["joint_angles"]),
                    joint_velocities=np.array(sg["joint_velocities"]),
                    club_pose=np.array(sg["club_pose"]),
                    applied_torques=np.array(sg["applied_torques"]),
                    metadata=meta,
                )
                self._sequences[seq_id] = seq  # disk wins on collision

        logger.info(
            "Loaded %d sequence(s) from %s",
            len(self._sequences),
            self._storage_path,
        )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _hdf5_key(sequence_id: str) -> str:
    """Convert a sequence ID to an HDF5-safe group key.

    HDF5 group names may not contain ``/``, so we replace it with ``__``.

    Args:
        sequence_id: Raw sequence identifier.

    Returns:
        HDF5-safe group name.
    """
    return sequence_id.replace("/", "__")
