"""Cross-engine FK equivalence test (issue #4542).

For each engine pair (MuJoCo, Drake, Pinocchio), load the same URDF
generated by the character builder, sample N random joint configurations
within their limits, and assert the end-effector positions agree across
engines within 5 mm RMSE.

Mirrors the motion-matching cross-engine equivalence gate
(``tests/motion_matching/test_cross_engine_equivalence.py``) for URDF
output of the character builder.

Each engine is gated by ``pytest.importorskip``; tests skip cleanly if
any engine in a pair is unavailable on the runner.
"""

from __future__ import annotations

import numpy as np
import pytest

hcb = pytest.importorskip("humanoid_character_builder")

EQUIVALENCE_THRESHOLD_MM = 5.0
N_RANDOM_CONFIGS = 25
RNG_SEED = 0xC0FFEE


@pytest.fixture(scope="module")
def average_urdf(tmp_path_factory: pytest.TempPathFactory) -> str:
    """Generate the 'average' preset URDF once and write to a tempfile."""
    builder = hcb.CharacterBuilder()
    try:
        params = builder.create_from_preset("average")
    except (KeyError, ValueError):
        pytest.skip("'average' preset not available in this build")
    urdf_xml = builder.generate_urdf(params)
    path = tmp_path_factory.mktemp("avg_") / "humanoid.urdf"
    path.write_text(urdf_xml, encoding="utf-8")
    return str(path)


def _sample_q(rng: np.random.Generator, nq: int) -> np.ndarray:
    """Random joint vector in a sane working range (radians)."""
    return rng.uniform(-0.5, 0.5, size=nq)


# ---------------------------------------------------------------------------
# MuJoCo vs Pinocchio
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_mujoco_vs_pinocchio_fk_within_5mm(average_urdf: str) -> None:
    """End-effector positions must agree within 5 mm RMSE between MuJoCo
    and Pinocchio for random joint configurations on the same URDF."""
    mujoco = pytest.importorskip("mujoco")
    pinocchio = pytest.importorskip("pinocchio")
    if not hasattr(pinocchio, "buildModelFromUrdf"):
        pytest.skip("pinocchio stub install (missing buildModelFromUrdf)")

    # MuJoCo
    mj_model = mujoco.MjModel.from_xml_path(average_urdf)
    mj_data = mujoco.MjData(mj_model)

    # Pinocchio
    pin_model = pinocchio.buildModelFromUrdf(average_urdf)
    pin_data = pin_model.createData()

    nq = min(mj_model.nq, pin_model.nq)
    if nq == 0:
        pytest.skip("URDF has no joint DOF; FK test not meaningful")

    rng = np.random.default_rng(RNG_SEED)

    # Pick the body whose position we'll compare. Use the last body in
    # MuJoCo (typically a hand or foot end effector). For Pinocchio,
    # use the corresponding frame name if available; fall back to the
    # last frame.
    mj_body_id = mj_model.nbody - 1
    pin_frame_id = pin_model.nframes - 1

    diffs_mm: list[float] = []
    for _ in range(N_RANDOM_CONFIGS):
        q = _sample_q(rng, nq)

        mj_data.qpos[:nq] = q
        mujoco.mj_forward(mj_model, mj_data)
        mj_pos = np.array(mj_data.xpos[mj_body_id])

        # Pinocchio expects a full-size q vector
        pin_q = np.zeros(pin_model.nq)
        pin_q[:nq] = q
        pinocchio.forwardKinematics(pin_model, pin_data, pin_q)
        pinocchio.updateFramePlacements(pin_model, pin_data)
        pin_pos = np.array(pin_data.oMf[pin_frame_id].translation)

        diff_mm = float(np.linalg.norm(mj_pos - pin_pos)) * 1000.0
        diffs_mm.append(diff_mm)

    rmse_mm = float(np.sqrt(np.mean(np.square(diffs_mm))))
    assert rmse_mm <= EQUIVALENCE_THRESHOLD_MM, (
        f"MuJoCo vs Pinocchio FK disagrees: RMSE={rmse_mm:.3f} mm "
        f"(threshold {EQUIVALENCE_THRESHOLD_MM} mm). "
        f"Per-config diffs: min={min(diffs_mm):.3f}, max={max(diffs_mm):.3f}"
    )


# ---------------------------------------------------------------------------
# MuJoCo vs Drake
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_mujoco_vs_drake_fk_within_5mm(average_urdf: str) -> None:
    """MuJoCo vs Drake FK equivalence on the same URDF."""
    mujoco = pytest.importorskip("mujoco")
    pytest.importorskip("pydrake.multibody.plant")
    try:
        from pydrake.multibody.parsing import Parser
        from pydrake.multibody.plant import MultibodyPlant
        from pydrake.systems.framework import DiagramBuilder
    except ImportError:
        pytest.skip("pydrake stub install (multibody not available)")

    # MuJoCo
    mj_model = mujoco.MjModel.from_xml_path(average_urdf)
    mj_data = mujoco.MjData(mj_model)

    # Drake
    builder = DiagramBuilder()
    plant = MultibodyPlant(time_step=0.0)
    plant.set_name("humanoid")
    Parser(plant).AddModels(average_urdf)
    plant.Finalize()
    diagram = builder.Build()
    context = diagram.CreateDefaultContext()
    plant_context = plant.GetMyContextFromRoot(context)

    nq = min(mj_model.nq, plant.num_positions())
    if nq == 0:
        pytest.skip("URDF has no joint DOF; FK test not meaningful")

    # Use the last body in each engine as the comparison target.
    mj_body_id = mj_model.nbody - 1
    drake_body = plant.get_body(
        plant.GetBodyIndices(plant.GetModelInstanceByName("humanoid"))[-1]
    )

    rng = np.random.default_rng(RNG_SEED)
    diffs_mm: list[float] = []

    for _ in range(N_RANDOM_CONFIGS):
        q = _sample_q(rng, nq)

        mj_data.qpos[:nq] = q
        mujoco.mj_forward(mj_model, mj_data)
        mj_pos = np.array(mj_data.xpos[mj_body_id])

        plant_q = np.zeros(plant.num_positions())
        plant_q[:nq] = q
        plant.SetPositions(plant_context, plant_q)
        drake_pose = plant.EvalBodyPoseInWorld(plant_context, drake_body)
        drake_pos = np.array(drake_pose.translation())

        diff_mm = float(np.linalg.norm(mj_pos - drake_pos)) * 1000.0
        diffs_mm.append(diff_mm)

    rmse_mm = float(np.sqrt(np.mean(np.square(diffs_mm))))
    assert rmse_mm <= EQUIVALENCE_THRESHOLD_MM, (
        f"MuJoCo vs Drake FK disagrees: RMSE={rmse_mm:.3f} mm "
        f"(threshold {EQUIVALENCE_THRESHOLD_MM} mm)."
    )


# ---------------------------------------------------------------------------
# Drake vs Pinocchio
# ---------------------------------------------------------------------------


@pytest.mark.integration
def test_drake_vs_pinocchio_fk_within_5mm(average_urdf: str) -> None:
    """Drake vs Pinocchio FK equivalence on the same URDF."""
    pytest.importorskip("pydrake.multibody.plant")
    pinocchio = pytest.importorskip("pinocchio")
    if not hasattr(pinocchio, "buildModelFromUrdf"):
        pytest.skip("pinocchio stub install")
    try:
        from pydrake.multibody.parsing import Parser
        from pydrake.multibody.plant import MultibodyPlant
        from pydrake.systems.framework import DiagramBuilder
    except ImportError:
        pytest.skip("pydrake stub install")

    # Drake
    builder = DiagramBuilder()
    plant = MultibodyPlant(time_step=0.0)
    plant.set_name("humanoid")
    Parser(plant).AddModels(average_urdf)
    plant.Finalize()
    diagram = builder.Build()
    context = diagram.CreateDefaultContext()
    plant_context = plant.GetMyContextFromRoot(context)

    # Pinocchio
    pin_model = pinocchio.buildModelFromUrdf(average_urdf)
    pin_data = pin_model.createData()

    nq = min(plant.num_positions(), pin_model.nq)
    if nq == 0:
        pytest.skip("URDF has no joint DOF; FK test not meaningful")

    drake_body = plant.get_body(
        plant.GetBodyIndices(plant.GetModelInstanceByName("humanoid"))[-1]
    )
    pin_frame_id = pin_model.nframes - 1

    rng = np.random.default_rng(RNG_SEED)
    diffs_mm: list[float] = []

    for _ in range(N_RANDOM_CONFIGS):
        q = _sample_q(rng, nq)

        plant_q = np.zeros(plant.num_positions())
        plant_q[:nq] = q
        plant.SetPositions(plant_context, plant_q)
        drake_pos = np.array(
            plant.EvalBodyPoseInWorld(plant_context, drake_body).translation()
        )

        pin_q = np.zeros(pin_model.nq)
        pin_q[:nq] = q
        pinocchio.forwardKinematics(pin_model, pin_data, pin_q)
        pinocchio.updateFramePlacements(pin_model, pin_data)
        pin_pos = np.array(pin_data.oMf[pin_frame_id].translation)

        diff_mm = float(np.linalg.norm(drake_pos - pin_pos)) * 1000.0
        diffs_mm.append(diff_mm)

    rmse_mm = float(np.sqrt(np.mean(np.square(diffs_mm))))
    assert rmse_mm <= EQUIVALENCE_THRESHOLD_MM, (
        f"Drake vs Pinocchio FK disagrees: RMSE={rmse_mm:.3f} mm "
        f"(threshold {EQUIVALENCE_THRESHOLD_MM} mm)."
    )
