# WARNING: DO NOT EDIT THIS FILE DIRECTLY.
# This file is a child copy that shadows or shares code with the Tools repository.
# Canonical changes must be made in the Tools repository under src/shared/python/
# and synchronized back to UpstreamDrift. Direct edits here risk being lost.


"""Backward-compatibility shim for the Two-Stage PSA System Analysis GUI.

The implementation was decomposed into the :mod:`.ui` package; this module
only re-exports that public surface and provides the ``main()`` entry point.
See #2310 for the wider architecture-debt extraction schedule.
"""

import sys

from PyQt6.QtWidgets import QApplication

# Expose components for backward compatibility
from .ui import (
    InputPanel,
    MplCanvas,
    PFDWidget,
    PSAMainWindow,
    ResultsPanel,
    SensitivityPlotWidget,
    create_slider,
)

__all__ = (
    "InputPanel",
    "ResultsPanel",
    "SensitivityPlotWidget",
    "PFDWidget",
    "PSAMainWindow",
    "create_slider",
    "MplCanvas",
    "main",
)


def main() -> None:
    """Main entry point for the GUI application."""
    from shared.python.theme import setup_themed_app

    app = QApplication(sys.argv)
    app.setStyle("Fusion")

    window = PSAMainWindow()
    setup_themed_app(app, window, settings_app="PSAPackage")
    window.show()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()
