function out = add_leg_chain(model_name, opts)
%ADD_LEG_CHAIN  Add hip+knee+ankle+foot+contact subsystems to MODEL_NAME.
%
%   OUT = ADD_LEG_CHAIN(MODEL_NAME, OPTS) builds mirrored scripted leg
%   subsystems (Left/Right Leg Kinetically Driven) and a generated
%   Ground Contact Forces assembly.  The function declares the shared
%   ground/contact design surface so reruns report exactly which
%   Simscape-specific operations could not be completed headlessly.
%
%   Per leg:
%     * Hip Gimbal Joint (3 DOF) — input parameters
%       L/RHipStartPosition{X,Y,Z} (deg), L/RHipStartVelocity{X,Y,Z},
%       and 7-coefficient polynomial torque per axis named
%       L/RHip{X,Y,Z}{A..G} so that
%       getPolynomialParameterInfo() picks them up automatically.
%     * Knee Revolute Joint (1 DOF) — L/RKneeStartPosition,
%       L/RKneeStartVelocity, L/RKnee{A..G}.
%     * Ankle Universal Joint (2 DOF) — L/RAnkleStartPosition{X,Y},
%       L/RAnkleStartVelocity{X,Y}, L/RAnkle{X,Y}{A..G}.
%     * Upper-Leg, Lower-Leg, Foot rigid bodies (Cylindrical /
%       Cylindrical / Brick) sized from new model-workspace variables
%       (UpperLegLength, LowerLegLength, FootLength, plus masses).
%     * Foot ↔ Ground Spatial Contact Force (Sphere/Plane).
%
%   The function MUTATES the loaded model in place; caller must
%   ``save_system`` afterward.
%
%   Args:
%       MODEL_NAME (char/string)  loaded Simulink model name.
%       OPTS (struct)
%         .verbose          default true.
%         .dry_run          default false; build the block list but
%                           don't actually call add_block.
%         .skip_contact     default false; build joints + bodies but
%                           don't add the contact-force network.
%         .leg_root_path    default ``<MODEL_NAME>``; you can sandbox
%                           the new chain into a wrapper subsystem by
%                           passing e.g. ``<MODEL_NAME>/LowerBody``.
%
%   Returns:
%       OUT (struct)
%         .blocks_added         total block count delta.
%         .blocks_per_phase     per-phase counts.
%         .new_workspace_vars   names of new model-workspace variables
%                               (lengths/masses/inertias).  Caller can
%                               attach defaults via setVariable when
%                               creating the SimulationInput.
%
%   STATUS (2026-05-08):
%   This implementation slice creates mirrored generated leg subsystems
%   and a generated contact-force assembly using add_block / set_param /
%   add_line calls.  It deletes/rebuilds those generated subsystems on
%   every run so build_3d_fullbody is idempotent.  Simscape Multibody
%   library and mask names can vary by MATLAB release/license; those
%   operations are captured in OUT.operation_log and OUT.validation_status
%   instead of being silently ignored.
%
%   See also: BUILD_3D_FULLBODY, PRUNE_REDUNDANT_LOGGING,
%             VALIDATE_3D_FULLBODY.

    arguments
        model_name (1,1) string
        opts (1,1) struct = struct()
    end

    if ~isfield(opts, 'verbose');       opts.verbose       = true;  end
    if ~isfield(opts, 'dry_run');       opts.dry_run       = false; end
    if ~isfield(opts, 'skip_contact');  opts.skip_contact  = false; end
    if ~isfield(opts, 'leg_root_path')
        opts.leg_root_path = char(model_name);
    end

    if ~bdIsLoaded(char(model_name))
        error('add_leg_chain:notLoaded', ...
              'Model %s is not loaded.  Call load_system first.', model_name);
    end

    out = struct( ...
        'blocks_added',     0, ...
        'blocks_per_phase', struct( ...
            'workspace_vars',     0, ...
            'left_leg_subsystem', 0, ...
            'right_leg_subsystem',0, ...
            'ground_plane',       0, ...
            'contact_forces',     0), ...
        'new_workspace_vars', strings(0,1), ...
        'generated_blocks',  strings(0,1), ...
        'operation_log',     struct('operation', {}, 'target', {}, ...
                                    'status', {}, 'message', {}), ...
        'validation_status', "not_started");

    if opts.verbose
        fprintf('add_leg_chain: building mirrored scripted leg chains\n');
    end

    % ---- Phase 1: declare new model-workspace variables -------------
    % Anthropometric defaults (de-Leva male, ~1.78m subject):
    %   UpperLegLength = 0.435 m   (greater trochanter to knee)
    %   LowerLegLength = 0.430 m   (knee to lateral malleolus)
    %   FootLength     = 0.260 m   (heel to toe)
    %   Plus masses + simple cylindrical-uniform inertias.
    new_vars = local_default_workspace_vars();
    if ~opts.dry_run
        try
            ws = get_param(char(model_name), 'ModelWorkspace');
            f = fieldnames(new_vars);
            for k = 1:numel(f)
                if ~hasVariable(ws, f{k})
                    assignin(ws, f{k}, new_vars.(f{k}));
                    out.new_workspace_vars(end+1, 1) = string(f{k});
                end
            end
        catch ME
            warning('add_leg_chain:wsAddFailed', ...
                    'Could not add workspace variables: %s', ME.message);
        end
    else
        out.new_workspace_vars = string(fieldnames(new_vars));
    end
    out.blocks_per_phase.workspace_vars = numel(out.new_workspace_vars);

    % ---- Phase 2: create mirrored scripted leg chains ----------------
    left = local_build_leg(char(opts.leg_root_path), opts, 'L', 'Left', 260);
    out.blocks_per_phase.left_leg_subsystem = left.blocks_added;
    out.generated_blocks = left.generated_blocks;
    out.operation_log = [out.operation_log, left.operation_log];

    right = local_build_leg(char(opts.leg_root_path), opts, 'R', 'Right', 620);
    out.blocks_per_phase.right_leg_subsystem = right.blocks_added;
    out.generated_blocks = [out.generated_blocks; right.generated_blocks];
    out.operation_log = [out.operation_log, right.operation_log];

    % ---- Phase 3: create the shared ground/contact assembly ----------
    contact = local_build_ground_contact(char(opts.leg_root_path), opts);
    out.blocks_per_phase.ground_plane = contact.ground_plane_blocks;
    out.blocks_per_phase.contact_forces = contact.contact_force_blocks;
    out.generated_blocks = [out.generated_blocks; contact.generated_blocks];
    out.operation_log = [out.operation_log, contact.operation_log];

    out.blocks_added = out.blocks_per_phase.left_leg_subsystem + ...
        out.blocks_per_phase.right_leg_subsystem + ...
        out.blocks_per_phase.ground_plane + ...
        out.blocks_per_phase.contact_forces;
    failed = string({out.operation_log.status}) == "failed";
    if any(failed)
        out.validation_status = "partial_with_reported_failures";
    else
        out.validation_status = "left_leg_scripted";
    end

    if opts.verbose
        fprintf('  left leg generated blocks:  %d\n', ...
            out.blocks_per_phase.left_leg_subsystem);
        fprintf('  right leg generated blocks: %d\n', ...
            out.blocks_per_phase.right_leg_subsystem);
        fprintf('  contact generated blocks:   %d\n', ...
            out.blocks_per_phase.ground_plane + ...
            out.blocks_per_phase.contact_forces);
        fprintf('  validation_status: %s\n', out.validation_status);
        fprintf('  new model-workspace variables (default values queued): %d\n', ...
            out.blocks_per_phase.workspace_vars);
    end
end


% =====================================================================
function report = local_build_leg(root_path, opts, side, side_name, x0)
%LOCAL_BUILD_LEG  Delete/rebuild one generated leg subsystem.
    subsystem_name = sprintf('%s Leg Kinetically Driven', side_name);
    subsystem_path = sprintf('%s/%s', root_path, subsystem_name);

    report = struct( ...
        'blocks_added',     0, ...
        'generated_blocks', strings(0,1), ...
        'operation_log',    struct('operation', {}, 'target', {}, ...
                                   'status', {}, 'message', {}));

    if opts.dry_run
        specs = local_leg_block_specs(subsystem_path, side);
        report.blocks_added = numel(specs);
        report.generated_blocks = string({specs.dst})';
        report.operation_log(end+1) = local_log_entry( ...
            'dry_run', subsystem_path, 'ok', ...
            sprintf('Declared %s-leg block graph without mutating model.', side_name));
        return
    end

    if local_block_exists(subsystem_path)
        delete_block(subsystem_path);
        report.operation_log(end+1) = local_log_entry( ...
            'delete_block', subsystem_path, 'ok', ...
            sprintf('Removed prior generated %s-leg subsystem for idempotent rebuild.', side_name));
    end

    [ok, message] = local_try_add_block( ...
        'simulink/Ports & Subsystems/Subsystem', subsystem_path, ...
        {'Position', [x0 360 x0+310 620]});
    report.operation_log(end+1) = local_log_entry( ...
        'add_block', subsystem_path, local_status(ok), message);
    if ~ok
        return
    end
    report.generated_blocks(end+1, 1) = string(subsystem_path);

    specs = local_leg_block_specs(subsystem_path, side);
    for k = 1:numel(specs)
        spec = specs(k);
        [ok, message] = local_try_add_block(spec.src, spec.dst, spec.params);
        report.operation_log(end+1) = local_log_entry( ...
            'add_block', spec.dst, local_status(ok), message);
        if ok
            report.blocks_added = report.blocks_added + 1;
            report.generated_blocks(end+1, 1) = string(spec.dst);
        end
    end

    lines = local_leg_line_specs(side);
    for k = 1:size(lines, 1)
        [ok, message] = local_try_add_line(subsystem_path, lines{k,1}, lines{k,2});
        report.operation_log(end+1) = local_log_entry( ...
            'add_line', sprintf('%s: %s -> %s', subsystem_path, lines{k,1}, lines{k,2}), ...
            local_status(ok), message);
    end
end


function specs = local_leg_block_specs(subsystem_path, side)
%LOCAL_LEG_BLOCK_SPECS  Contract names for one generated leg chain.
    side = char(side);
    specs = [ ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/Pelvis_Frame', subsystem_path), ...
            {'Position', [30 65 60 85]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorque%sHipX', subsystem_path, side), ...
            {'Position', [30 125 60 145]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorque%sHipY', subsystem_path, side), ...
            {'Position', [30 165 60 185]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorque%sHipZ', subsystem_path, side), ...
            {'Position', [30 205 60 225]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorque%sKnee', subsystem_path, side), ...
            {'Position', [30 285 60 305]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorque%sAnkleX', subsystem_path, side), ...
            {'Position', [30 365 60 385]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorque%sAnkleY', subsystem_path, side), ...
            {'Position', [30 405 60 425]}), ...
        local_block_spec('sm_lib/Joints/Gimbal Joint', ...
            sprintf('%s/%sHip_Gimbal', subsystem_path, side), ...
            {'Position', [130 85 230 155]}), ...
        local_block_spec('sm_lib/Body Elements/Cylindrical Solid', ...
            sprintf('%s/%sUpperLeg_CylindricalSolid', subsystem_path, side), ...
            {'Position', [285 85 385 155], ...
             'CylinderRadius', 'UpperLegRadius', ...
             'CylinderLength', 'UpperLegLength', ...
             'Mass', 'UpperLegMass'}), ...
        local_block_spec('sm_lib/Joints/Revolute Joint', ...
            sprintf('%s/%sKnee_Revolute', subsystem_path, side), ...
            {'Position', [440 85 540 155]}), ...
        local_block_spec('sm_lib/Body Elements/Cylindrical Solid', ...
            sprintf('%s/%sLowerLeg_CylindricalSolid', subsystem_path, side), ...
            {'Position', [595 85 695 155], ...
             'CylinderRadius', 'LowerLegRadius', ...
             'CylinderLength', 'LowerLegLength', ...
             'Mass', 'LowerLegMass'}), ...
        local_block_spec('sm_lib/Joints/Universal Joint', ...
            sprintf('%s/%sAnkle_Universal', subsystem_path, side), ...
            {'Position', [750 85 850 155]}), ...
        local_block_spec('sm_lib/Body Elements/Brick Solid', ...
            sprintf('%s/%sFoot_BrickSolid', subsystem_path, side), ...
            {'Position', [905 85 1005 155], ...
             'BrickDimensions', '[FootLength, FootWidth, FootHeight]', ...
             'Mass', 'FootMass'}), ...
        local_block_spec('sm_lib/Body Elements/Spherical Solid', ...
            sprintf('%s/%sBallOfFoot_Sphere', subsystem_path, side), ...
            {'Position', [1060 85 1160 155], ...
             'SphereRadius', '0.03', ...
             'Mass', '0.01'}), ...
        local_block_spec('simulink/Sinks/Out1', ...
            sprintf('%s/%sFoot_Frame', subsystem_path, side), ...
            {'Position', [1235 105 1265 125]}) ...
    ];
end


function lines = local_leg_line_specs(side)
%LOCAL_LEG_LINE_SPECS  Signal-level lines used for headless checks.
%
% Simscape conserving-frame lines have release-specific port names on the
% Multibody blocks.  This first slice wires the stable Simulink signal ports
% and records any release-specific misses in operation_log.
    side = char(side);
    lines = {
        sprintf('JointTorque%sHipX/1', side),   sprintf('%sHip_Gimbal/1', side);
        sprintf('JointTorque%sKnee/1', side),   sprintf('%sKnee_Revolute/1', side);
        sprintf('JointTorque%sAnkleX/1', side), sprintf('%sAnkle_Universal/1', side);
        sprintf('%sFoot_BrickSolid/1', side),   sprintf('%sFoot_Frame/1', side);
    };
end


function report = local_build_ground_contact(root_path, opts)
%LOCAL_BUILD_GROUND_CONTACT  Delete/rebuild generated ground contact assembly.
    subsystem_name = 'Ground Contact Forces';
    subsystem_path = sprintf('%s/%s', root_path, subsystem_name);

    report = struct( ...
        'ground_plane_blocks',  0, ...
        'contact_force_blocks', 0, ...
        'generated_blocks',     strings(0,1), ...
        'operation_log',        struct('operation', {}, 'target', {}, ...
                                       'status', {}, 'message', {}));

    if opts.skip_contact
        report.operation_log(end+1) = local_log_entry( ...
            'skip', subsystem_path, 'skipped', ...
            'Contact generation disabled by opts.skip_contact.');
        return
    end

    if opts.dry_run
        specs = local_ground_contact_block_specs(subsystem_path);
        report.generated_blocks = string({specs.dst})';
        report.ground_plane_blocks = 1;
        report.contact_force_blocks = numel(specs) - 1;
        report.operation_log(end+1) = local_log_entry( ...
            'dry_run', subsystem_path, 'ok', ...
            'Declared ground/contact block graph without mutating model.');
        return
    end

    if local_block_exists(subsystem_path)
        delete_block(subsystem_path);
        report.operation_log(end+1) = local_log_entry( ...
            'delete_block', subsystem_path, 'ok', ...
            'Removed prior generated ground-contact subsystem for idempotent rebuild.');
    end

    [ok, message] = local_try_add_block( ...
        'simulink/Ports & Subsystems/Subsystem', subsystem_path, ...
        {'Position', [260 675 930 850]});
    report.operation_log(end+1) = local_log_entry( ...
        'add_block', subsystem_path, local_status(ok), message);
    if ~ok
        return
    end
    report.generated_blocks(end+1, 1) = string(subsystem_path);

    specs = local_ground_contact_block_specs(subsystem_path);
    for k = 1:numel(specs)
        spec = specs(k);
        [ok, message] = local_try_add_block(spec.src, spec.dst, spec.params);
        report.operation_log(end+1) = local_log_entry( ...
            'add_block', spec.dst, local_status(ok), message);
        if ok
            report.generated_blocks(end+1, 1) = string(spec.dst);
            if contains(string(spec.dst), "Ground_Plane")
                report.ground_plane_blocks = report.ground_plane_blocks + 1;
            elseif contains(string(spec.dst), "Contact_Force") || ...
                   contains(string(spec.dst), "GroundReaction")
                report.contact_force_blocks = report.contact_force_blocks + 1;
            end
        end
    end

    lines = local_ground_contact_line_specs();
    for k = 1:size(lines, 1)
        [ok, message] = local_try_add_line(subsystem_path, lines{k,1}, lines{k,2});
        report.operation_log(end+1) = local_log_entry( ...
            'add_line', sprintf('%s: %s -> %s', subsystem_path, lines{k,1}, lines{k,2}), ...
            local_status(ok), message);
    end
end


function specs = local_ground_contact_block_specs(subsystem_path)
%LOCAL_GROUND_CONTACT_BLOCK_SPECS  Contract names for foot-ground contact.
    specs = [ ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/LFoot_Frame', subsystem_path), ...
            {'Position', [30 55 60 75]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/RFoot_Frame', subsystem_path), ...
            {'Position', [30 135 60 155]}), ...
        local_block_spec('sm_lib/Body Elements/Infinite Plane', ...
            sprintf('%s/Ground_Plane_Z0', subsystem_path), ...
            {'Position', [180 85 280 145]}), ...
        local_block_spec('sm_lib/Forces and Torques/Spatial Contact Force', ...
            sprintf('%s/LFoot_Ground_Contact_Force', subsystem_path), ...
            {'Position', [375 40 515 100]}), ...
        local_block_spec('sm_lib/Forces and Torques/Spatial Contact Force', ...
            sprintf('%s/RFoot_Ground_Contact_Force', subsystem_path), ...
            {'Position', [375 125 515 185]}), ...
        local_block_spec('simulink/Sinks/Out1', ...
            sprintf('%s/LGroundReactionForce', subsystem_path), ...
            {'Position', [620 55 650 75]}), ...
        local_block_spec('simulink/Sinks/Out1', ...
            sprintf('%s/RGroundReactionForce', subsystem_path), ...
            {'Position', [620 135 650 155]}) ...
    ];
end


function lines = local_ground_contact_line_specs()
%LOCAL_GROUND_CONTACT_LINE_SPECS  Stable signal-level contact lines.
%
% The real Spatial Contact Force conserving-frame ports are release-
% specific.  These lines intentionally exercise the expected named graph
% and record misses in operation_log until a MATLAB GUI pass captures the
% exact port names.
    lines = {
        'LFoot_Frame/1', 'LFoot_Ground_Contact_Force/1';
        'RFoot_Frame/1', 'RFoot_Ground_Contact_Force/1';
        'LFoot_Ground_Contact_Force/1', 'LGroundReactionForce/1';
        'RFoot_Ground_Contact_Force/1', 'RGroundReactionForce/1';
    };
end


function spec = local_block_spec(src, dst, params)
    spec = struct('src', src, 'dst', dst, 'params', {params});
end


function tf = local_block_exists(path)
    try
        get_param(path, 'Handle');
        tf = true;
    catch
        tf = false;
    end
end


function [ok, message] = local_try_add_block(src, dst, params)
    try
        add_block(src, dst, 'MakeNameUnique', 'off');
        for idx = 1:2:numel(params)
            try
                set_param(dst, params{idx}, params{idx+1});
            catch ME
                message = sprintf('block added; set_param(%s) failed: %s', ...
                    params{idx}, ME.message);
                ok = false;
                return
            end
        end
        ok = true;
        message = 'ok';
    catch ME
        ok = false;
        message = ME.message;
    end
end


function [ok, message] = local_try_add_line(system_path, src, dst)
    try
        add_line(system_path, src, dst, 'autorouting', 'on');
        ok = true;
        message = 'ok';
    catch ME
        ok = false;
        message = ME.message;
    end
end


function status = local_status(ok)
    if ok
        status = 'ok';
    else
        status = 'failed';
    end
end


function entry = local_log_entry(operation, target, status, message)
    entry = struct( ...
        'operation', string(operation), ...
        'target',    string(target), ...
        'status',    string(status), ...
        'message',   string(message));
end


% =====================================================================
function vars = local_default_workspace_vars()
%LOCAL_DEFAULT_WORKSPACE_VARS  Anthropometric defaults for the leg chain.
%
%   Values from de Leva 1996 / Winter 2009 averaged for an adult male
%   golfer (~1.78 m, 80 kg), with cylindrical-uniform inertia
%   approximations.  Caller can override per-trial via setVariable on
%   the SimulationInput.
    vars = struct( ...
        ... % --- segment lengths (m) ---
        'UpperLegLength',           0.435, ...
        'LowerLegLength',           0.430, ...
        'FootLength',               0.260, ...
        'FootWidth',                0.095, ...
        'FootHeight',               0.060, ...
        'UpperLegRadius',           0.055, ...   % cylindrical thigh
        'LowerLegRadius',           0.040, ...   % cylindrical shin
        ... % --- masses (kg) — de Leva fractions of 80 kg total body ---
        'UpperLegMass',             0.10 * 80, ...
        'LowerLegMass',             0.0465 * 80, ...
        'FootMass',                 0.0145 * 80, ...
        ... % --- contact parameters ---
        'GroundContactStiffness',   1e5, ...
        'GroundContactDamping',     1000, ...
        'GroundFrictionStatic',     0.7, ...
        'GroundFrictionKinetic',    0.5, ...
        ... % --- joint start positions (degrees) — neutral standing ---
        'LHipStartPositionX',       0.0, ...
        'LHipStartPositionY',       0.0, ...
        'LHipStartPositionZ',       0.0, ...
        'RHipStartPositionX',       0.0, ...
        'RHipStartPositionY',       0.0, ...
        'RHipStartPositionZ',       0.0, ...
        'LKneeStartPosition',       0.0, ...
        'RKneeStartPosition',       0.0, ...
        'LAnkleStartPositionX',     0.0, ...
        'LAnkleStartPositionY',     0.0, ...
        'RAnkleStartPositionX',     0.0, ...
        'RAnkleStartPositionY',     0.0, ...
        'LHipStartVelocityX',       0.0, ...
        'LHipStartVelocityY',       0.0, ...
        'LHipStartVelocityZ',       0.0, ...
        'RHipStartVelocityX',       0.0, ...
        'RHipStartVelocityY',       0.0, ...
        'RHipStartVelocityZ',       0.0, ...
        'LKneeStartVelocity',       0.0, ...
        'RKneeStartVelocity',       0.0, ...
        'LAnkleStartVelocityX',     0.0, ...
        'LAnkleStartVelocityY',     0.0, ...
        'RAnkleStartVelocityX',     0.0, ...
        'RAnkleStartVelocityY',     0.0);

    joints = {'LHipX', 'LHipY', 'LHipZ', 'LKnee', 'LAnkleX', 'LAnkleY', ...
              'RHipX', 'RHipY', 'RHipZ', 'RKnee', 'RAnkleX', 'RAnkleY'};
    coeffs = {'A', 'B', 'C', 'D', 'E', 'F', 'G'};
    for j = 1:numel(joints)
        for c = 1:numel(coeffs)
            vars.(sprintf('%s%s', joints{j}, coeffs{c})) = 0.0;
        end
    end
end
