function out = add_leg_chain(model_name, opts)
%ADD_LEG_CHAIN  Add hip+knee+ankle+foot+contact subsystems to MODEL_NAME.
%
%   OUT = ADD_LEG_CHAIN(MODEL_NAME, OPTS) builds the first scripted leg
%   subsystem (Left Leg Kinetically Driven) before the right-side mirror
%   is added in a follow-up.  The function also declares the shared
%   ground/contact design surface so reruns report exactly which
%   Simscape-specific operations could not be completed headlessly.
%
%   Per leg:
%     * Hip Gimbal Joint (3 DOF) — input parameters
%       L/RHipStartPosition{X,Y,Z} (deg), L/RHipStartVelocity{X,Y,Z},
%       and 7-coefficient polynomial torque per axis named
%       L/RHip{X,Y,Z}{A..G} so that
%       getPolynomialParameterInfo() picks them up automatically.
%     * Knee Revolute Joint (1 DOF) — L/RKneeStartPosition,
%       L/RKneeStartVelocity, L/RKnee{A..G}.
%     * Ankle Universal Joint (2 DOF) — L/RAnkleStartPosition{X,Y},
%       L/RAnkleStartVelocity{X,Y}, L/RAnkle{X,Y}{A..G}.
%     * Upper-Leg, Lower-Leg, Foot rigid bodies (Cylindrical /
%       Cylindrical / Brick) sized from new model-workspace variables
%       (UpperLegLength, LowerLegLength, FootLength, plus masses).
%     * Foot ↔ Ground Spatial Contact Force (Sphere/Plane).
%
%   The function MUTATES the loaded model in place; caller must
%   ``save_system`` afterward.
%
%   Args:
%       MODEL_NAME (char/string)  loaded Simulink model name.
%       OPTS (struct)
%         .verbose          default true.
%         .dry_run          default false; build the block list but
%                           don't actually call add_block.
%         .skip_contact     default false; build joints + bodies but
%                           don't add the contact-force network.
%         .leg_root_path    default ``<MODEL_NAME>``; you can sandbox
%                           the new chain into a wrapper subsystem by
%                           passing e.g. ``<MODEL_NAME>/LowerBody``.
%
%   Returns:
%       OUT (struct)
%         .blocks_added         total block count delta.
%         .blocks_per_phase     per-phase counts.
%         .new_workspace_vars   names of new model-workspace variables
%                               (lengths/masses/inertias).  Caller can
%                               attach defaults via setVariable when
%                               creating the SimulationInput.
%
%   STATUS (2026-05-08):
%   This is the first implementation slice.  It creates one generated
%   left-leg subsystem using add_block / set_param / add_line calls, and
%   it deletes/rebuilds that generated subsystem on every run so
%   build_3d_fullbody is idempotent.  Simscape Multibody library and mask
%   names can vary by MATLAB release/license; those operations are
%   captured in OUT.operation_log and OUT.validation_status instead of
%   being silently ignored.
%
%   See also: BUILD_3D_FULLBODY, PRUNE_REDUNDANT_LOGGING,
%             VALIDATE_3D_FULLBODY.

    arguments
        model_name (1,1) string
        opts (1,1) struct = struct()
    end

    if ~isfield(opts, 'verbose');       opts.verbose       = true;  end
    if ~isfield(opts, 'dry_run');       opts.dry_run       = false; end
    if ~isfield(opts, 'skip_contact');  opts.skip_contact  = false; end
    if ~isfield(opts, 'leg_root_path')
        opts.leg_root_path = char(model_name);
    end

    if ~bdIsLoaded(char(model_name))
        error('add_leg_chain:notLoaded', ...
              'Model %s is not loaded.  Call load_system first.', model_name);
    end

    out = struct( ...
        'blocks_added',     0, ...
        'blocks_per_phase', struct( ...
            'workspace_vars',     0, ...
            'left_leg_subsystem', 0, ...
            'right_leg_subsystem',0, ...
            'ground_plane',       0, ...
            'contact_forces',     0), ...
        'new_workspace_vars', strings(0,1), ...
        'generated_blocks',  strings(0,1), ...
        'operation_log',     struct('operation', {}, 'target', {}, ...
                                    'status', {}, 'message', {}), ...
        'validation_status', "not_started");

    if opts.verbose
        fprintf('add_leg_chain: building one scripted left leg chain\n');
    end

    % ---- Phase 1: declare new model-workspace variables -------------
    % Anthropometric defaults (de-Leva male, ~1.78m subject):
    %   UpperLegLength = 0.435 m   (greater trochanter to knee)
    %   LowerLegLength = 0.430 m   (knee to lateral malleolus)
    %   FootLength     = 0.260 m   (heel to toe)
    %   Plus masses + simple cylindrical-uniform inertias.
    new_vars = local_default_workspace_vars();
    if ~opts.dry_run
        try
            ws = get_param(char(model_name), 'ModelWorkspace');
            f = fieldnames(new_vars);
            for k = 1:numel(f)
                if ~hasVariable(ws, f{k})
                    assignin(ws, f{k}, new_vars.(f{k}));
                    out.new_workspace_vars(end+1, 1) = string(f{k});
                end
            end
        catch ME
            warning('add_leg_chain:wsAddFailed', ...
                    'Could not add workspace variables: %s', ME.message);
        end
    else
        out.new_workspace_vars = string(fieldnames(new_vars));
    end
    out.blocks_per_phase.workspace_vars = numel(out.new_workspace_vars);

    % ---- Phase 2: create the first scripted leg chain ----------------
    left = local_build_left_leg(char(opts.leg_root_path), opts);
    out.blocks_per_phase.left_leg_subsystem = left.blocks_added;
    out.generated_blocks = left.generated_blocks;
    out.operation_log = [out.operation_log, left.operation_log];

    % ---- Phase 3-5: report deferred mirror/contact phases ------------
    out.blocks_per_phase.right_leg_subsystem = 0;
    out.blocks_per_phase.ground_plane = 0;
    out.blocks_per_phase.contact_forces = 0;
    out.operation_log(end+1) = local_log_entry( ...
        'defer', 'Right Leg Kinetically Driven', 'deferred', ...
        'Right-side mirror is intentionally left for the next issue slice.');
    out.operation_log(end+1) = local_log_entry( ...
        'defer', 'Ground Plane + LFoot Contact Force', 'deferred', ...
        'Sphere-plane contact waits for a Simscape-validated frame-port pass.');

    out.blocks_added = out.blocks_per_phase.left_leg_subsystem + ...
        out.blocks_per_phase.right_leg_subsystem + ...
        out.blocks_per_phase.ground_plane + ...
        out.blocks_per_phase.contact_forces;
    failed = string({out.operation_log.status}) == "failed";
    if any(failed)
        out.validation_status = "partial_with_reported_failures";
    else
        out.validation_status = "left_leg_scripted";
    end

    if opts.verbose
        fprintf('  left leg generated blocks: %d\n', ...
            out.blocks_per_phase.left_leg_subsystem);
        fprintf('  validation_status: %s\n', out.validation_status);
        fprintf('  new model-workspace variables (default values queued): %d\n', ...
            out.blocks_per_phase.workspace_vars);
    end
end


% =====================================================================
function report = local_build_left_leg(root_path, opts)
%LOCAL_BUILD_LEFT_LEG  Delete/rebuild the generated left leg subsystem.
    subsystem_name = 'Left Leg Kinetically Driven';
    subsystem_path = sprintf('%s/%s', root_path, subsystem_name);

    report = struct( ...
        'blocks_added',     0, ...
        'generated_blocks', strings(0,1), ...
        'operation_log',    struct('operation', {}, 'target', {}, ...
                                   'status', {}, 'message', {}));

    if opts.dry_run
        specs = local_left_leg_block_specs(subsystem_path);
        report.blocks_added = numel(specs);
        report.generated_blocks = string({specs.dst})';
        report.operation_log(end+1) = local_log_entry( ...
            'dry_run', subsystem_path, 'ok', ...
            'Declared left-leg block graph without mutating model.');
        return
    end

    if local_block_exists(subsystem_path)
        delete_block(subsystem_path);
        report.operation_log(end+1) = local_log_entry( ...
            'delete_block', subsystem_path, 'ok', ...
            'Removed prior generated left-leg subsystem for idempotent rebuild.');
    end

    [ok, message] = local_try_add_block( ...
        'simulink/Ports & Subsystems/Subsystem', subsystem_path, ...
        {'Position', [260 360 570 620]});
    report.operation_log(end+1) = local_log_entry( ...
        'add_block', subsystem_path, local_status(ok), message);
    if ~ok
        return
    end
    report.generated_blocks(end+1, 1) = string(subsystem_path);

    specs = local_left_leg_block_specs(subsystem_path);
    for k = 1:numel(specs)
        spec = specs(k);
        [ok, message] = local_try_add_block(spec.src, spec.dst, spec.params);
        report.operation_log(end+1) = local_log_entry( ...
            'add_block', spec.dst, local_status(ok), message);
        if ok
            report.blocks_added = report.blocks_added + 1;
            report.generated_blocks(end+1, 1) = string(spec.dst);
        end
    end

    lines = local_left_leg_line_specs();
    for k = 1:size(lines, 1)
        [ok, message] = local_try_add_line(subsystem_path, lines{k,1}, lines{k,2});
        report.operation_log(end+1) = local_log_entry( ...
            'add_line', sprintf('%s: %s -> %s', subsystem_path, lines{k,1}, lines{k,2}), ...
            local_status(ok), message);
    end
end


function specs = local_left_leg_block_specs(subsystem_path)
%LOCAL_LEFT_LEG_BLOCK_SPECS  Contract names for the first leg chain slice.
    specs = [ ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/Pelvis_Frame', subsystem_path), ...
            {'Position', [30 65 60 85]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorqueLHipX', subsystem_path), ...
            {'Position', [30 125 60 145]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorqueLHipY', subsystem_path), ...
            {'Position', [30 165 60 185]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorqueLHipZ', subsystem_path), ...
            {'Position', [30 205 60 225]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorqueLKnee', subsystem_path), ...
            {'Position', [30 285 60 305]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorqueLAnkleX', subsystem_path), ...
            {'Position', [30 365 60 385]}), ...
        local_block_spec('simulink/Sources/In1', ...
            sprintf('%s/JointTorqueLAnkleY', subsystem_path), ...
            {'Position', [30 405 60 425]}), ...
        local_block_spec('sm_lib/Joints/Gimbal Joint', ...
            sprintf('%s/LHip_Gimbal', subsystem_path), ...
            {'Position', [130 85 230 155]}), ...
        local_block_spec('sm_lib/Body Elements/Cylindrical Solid', ...
            sprintf('%s/LUpperLeg_CylindricalSolid', subsystem_path), ...
            {'Position', [285 85 385 155], ...
             'CylinderRadius', 'UpperLegRadius', ...
             'CylinderLength', 'UpperLegLength', ...
             'Mass', 'UpperLegMass'}), ...
        local_block_spec('sm_lib/Joints/Revolute Joint', ...
            sprintf('%s/LKnee_Revolute', subsystem_path), ...
            {'Position', [440 85 540 155]}), ...
        local_block_spec('sm_lib/Body Elements/Cylindrical Solid', ...
            sprintf('%s/LLowerLeg_CylindricalSolid', subsystem_path), ...
            {'Position', [595 85 695 155], ...
             'CylinderRadius', 'LowerLegRadius', ...
             'CylinderLength', 'LowerLegLength', ...
             'Mass', 'LowerLegMass'}), ...
        local_block_spec('sm_lib/Joints/Universal Joint', ...
            sprintf('%s/LAnkle_Universal', subsystem_path), ...
            {'Position', [750 85 850 155]}), ...
        local_block_spec('sm_lib/Body Elements/Brick Solid', ...
            sprintf('%s/LFoot_BrickSolid', subsystem_path), ...
            {'Position', [905 85 1005 155], ...
             'BrickDimensions', '[FootLength, FootWidth, FootHeight]', ...
             'Mass', 'FootMass'}), ...
        local_block_spec('sm_lib/Body Elements/Spherical Solid', ...
            sprintf('%s/LBallOfFoot_Sphere', subsystem_path), ...
            {'Position', [1060 85 1160 155], ...
             'SphereRadius', '0.03', ...
             'Mass', '0.01'}), ...
        local_block_spec('simulink/Sinks/Out1', ...
            sprintf('%s/LFoot_Frame', subsystem_path), ...
            {'Position', [1235 105 1265 125]}) ...
    ];
end


function lines = local_left_leg_line_specs()
%LOCAL_LEFT_LEG_LINE_SPECS  Signal-level lines used for headless checks.
%
% Simscape conserving-frame lines have release-specific port names on the
% Multibody blocks.  This first slice wires the stable Simulink signal ports
% and records any release-specific misses in operation_log.
    lines = {
        'JointTorqueLHipX/1',   'LHip_Gimbal/1';
        'JointTorqueLKnee/1',   'LKnee_Revolute/1';
        'JointTorqueLAnkleX/1', 'LAnkle_Universal/1';
        'LFoot_BrickSolid/1',   'LFoot_Frame/1';
    };
end


function spec = local_block_spec(src, dst, params)
    spec = struct('src', src, 'dst', dst, 'params', {params});
end


function tf = local_block_exists(path)
    try
        get_param(path, 'Handle');
        tf = true;
    catch
        tf = false;
    end
end


function [ok, message] = local_try_add_block(src, dst, params)
    try
        add_block(src, dst, 'MakeNameUnique', 'off');
        for idx = 1:2:numel(params)
            try
                set_param(dst, params{idx}, params{idx+1});
            catch ME
                message = sprintf('block added; set_param(%s) failed: %s', ...
                    params{idx}, ME.message);
                ok = false;
                return
            end
        end
        ok = true;
        message = 'ok';
    catch ME
        ok = false;
        message = ME.message;
    end
end


function [ok, message] = local_try_add_line(system_path, src, dst)
    try
        add_line(system_path, src, dst, 'autorouting', 'on');
        ok = true;
        message = 'ok';
    catch ME
        ok = false;
        message = ME.message;
    end
end


function status = local_status(ok)
    if ok
        status = 'ok';
    else
        status = 'failed';
    end
end


function entry = local_log_entry(operation, target, status, message)
    entry = struct( ...
        'operation', string(operation), ...
        'target',    string(target), ...
        'status',    string(status), ...
        'message',   string(message));
end


% =====================================================================
function vars = local_default_workspace_vars()
%LOCAL_DEFAULT_WORKSPACE_VARS  Anthropometric defaults for the leg chain.
%
%   Values from de Leva 1996 / Winter 2009 averaged for an adult male
%   golfer (~1.78 m, 80 kg), with cylindrical-uniform inertia
%   approximations.  Caller can override per-trial via setVariable on
%   the SimulationInput.
    vars = struct( ...
        ... % --- segment lengths (m) ---
        'UpperLegLength',           0.435, ...
        'LowerLegLength',           0.430, ...
        'FootLength',               0.260, ...
        'FootWidth',                0.095, ...
        'FootHeight',               0.060, ...
        'UpperLegRadius',           0.055, ...   % cylindrical thigh
        'LowerLegRadius',           0.040, ...   % cylindrical shin
        ... % --- masses (kg) — de Leva fractions of 80 kg total body ---
        'UpperLegMass',             0.10 * 80, ...
        'LowerLegMass',             0.0465 * 80, ...
        'FootMass',                 0.0145 * 80, ...
        ... % --- contact parameters ---
        'GroundContactStiffness',   1e5, ...
        'GroundContactDamping',     1000, ...
        'GroundFrictionStatic',     0.7, ...
        'GroundFrictionKinetic',    0.5, ...
        ... % --- joint start positions (degrees) — neutral standing ---
        'LHipStartPositionX',       0.0, ...
        'LHipStartPositionY',       0.0, ...
        'LHipStartPositionZ',       0.0, ...
        'RHipStartPositionX',       0.0, ...
        'RHipStartPositionY',       0.0, ...
        'RHipStartPositionZ',       0.0, ...
        'LKneeStartPosition',       0.0, ...
        'RKneeStartPosition',       0.0, ...
        'LAnkleStartPositionX',     0.0, ...
        'LAnkleStartPositionY',     0.0, ...
        'RAnkleStartPositionX',     0.0, ...
        'RAnkleStartPositionY',     0.0);
end
